# Generated by Django 4.2 on 2024-07-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purcharse', '0003_purchase_change_purchase_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='change',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='price',
        ),
    ]
