# Generated by Django 4.2 on 2024-07-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_webauthncredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
    ]
