# Generated by Django 4.2 on 2024-06-30 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iva_image_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 36, 41, 439595, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
