# Generated by Django 4.2 on 2024-07-12 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 3, 38, 32, 638576, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
