# Generated by Django 4.2 on 2024-07-12 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 4, 0, 45, 216407, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
