# Generated by Django 4.2 on 2024-07-18 00:37

import datetime
import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[proy_sales.utils.valida_ruc], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[proy_sales.utils.valida_cedula], verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Caracteres inválidos para un número de teléfono.', regex='^\\d{9,15}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 0, 37, 35, 59112, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
