# Generated by Django 4.2 on 2024-07-19 03:47

import datetime
from django.db import migrations, models
import django.utils.timezone
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_company_dni_alter_customer_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacture_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Elaboración'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 3, 47, 55, 987523, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100, validators=[proy_sales.utils.valida_numero_entero_positivo], verbose_name='Stock'),
        ),
    ]
