# Generated by Django 4.2 on 2024-07-21 17:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_manufacture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 17, 16, 21, 499362, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Elaboración'),
        ),
        migrations.AlterField(
            model_name='productpricedetail',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Emision'),
        ),
    ]
