# Generated by Django 4.2 on 2024-07-22 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 5, 5, 50, 438072, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
